project_id = "yjchomutartdkzulzsyw"

[functions.generate-blog-image]
verify_jwt = true

[functions.track-analytics]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.check-funnel-alerts]
verify_jwt = true

[functions.analyze-funnel]
verify_jwt = true

[functions.generate-blog-article]
verify_jwt = true

[functions.generate-content-material]
verify_jwt = true
